apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: tiltaksgjennomforing-varsel-alert
  labels:
    team: arbeidsgiver
spec:
  receivers:
    slack:
      channel: 'arbeidsgiver-tiltak-alerts'
      prependText: ''
  alerts:
    - alert: applikasjon nede
      expr: up{app="tiltaksgjennomforing-varsel", job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"