apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-varsel
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/tiltaksgjennomforing-varsel:{{version}}
  team: teamtag
  port: 8081
  liveness:
    path: /tiltaksgjennomforing-varsel/healthcheck
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /tiltaksgjennomforing-varsel/healthcheck
    initialDelay: 30
    timeout: 1
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-varsel/actuator/prometheus