apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tiltaksgjennomforing-varsel
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 8081
  liveness:
    path: /tiltaksgjennomforing-varsel/healthcheck
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /tiltaksgjennomforing-varsel/healthcheck
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
  vault:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring-profil}}
  webproxy: true
  prometheus:
    enabled: true
    path: /tiltaksgjennomforing-varsel/actuator/prometheus