spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://b27dbvl033.preprod.local:5432/tiltaksgjennomforing-varsel-p15-preprod'

tiltaksgjennomforing:
  database:
    database-navn: tiltaksgjennomforing-varsel-p15-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  altinn-varsel:
    uri: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/notificationagencyexternalbasic/v1
    system-bruker: ${TILTAKSGJENNOMFORING_ALTINN_VARSEL_SYSTEM_BRUKER}
    system-passord: ${TILTAKSGJENNOMFORING_ALTINN_VARSEL_SYSTEM_PASSORD}
  sts:
    username: ${TILTAKSGJENNOMFORING_SERVICEUSER_USERNAME}
    password: ${TILTAKSGJENNOMFORING_SERVICEUSER_PASSWORD}
    ws-uri: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
