spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver

tiltaksgjennomforing:
  database:
    database-navn: tiltaksgjennomforing-varsel-prod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/prod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  altinn-varsel:
    uri: https://pep-gw.oera.no:9443/ekstern/altinn/notificationagencyexternalbasic/v1
  sts:
    username: ${tiltaksgjennomforing.serviceuser.username}
    password: ${tiltaksgjennomforing.serviceuser.password}
    ws-uri: https://sts.adeo.no/SecurityTokenServiceProvider/