spring:
  application:
    name: tiltaksgjennomforing-varsel-aiven
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
  kafka:
    consumer:
      group-id: tiltaksgjennomforing-varsel-aiven
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}

tiltaksgjennomforing:
  topics:
    sms: arbeidsgiver.tiltak-sms
    sms-resultat: arbeidsgiver.tiltak-sms-resultat
  database:
    database-navn: tiltaksgjennomforing-varsel-preprod
    database-url: ${spring.datasource.url}
    vault-sti: postgresql/preprod-fss
    minimum-idle: 1
    maximum-pool-size: 2
    max-lifetime: 300000
  altinn-varsel:
    uri: https://pep-gw-q1.oera-q.local:9443/ekstern/altinn/notificationagencyexternalbasic/v1
  sts:
    username: ${tiltaksgjennomforing.serviceuser.username}
    password: ${tiltaksgjennomforing.serviceuser.password}
    ws-uri: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
  unleash:
    unleash-uri: https://unleash.nais.io/api/