name: Bygg og deploy master

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Bygg
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Oppsett Java 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Bygg og test med Maven
        run: mvn package -B -Dsurefire.useFile=false

      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: arbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy til dev
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til dev-fss
        env:
          CLUSTER: dev-fss
          RESOURCE: nais.yaml
          VAR: spring-profil=preprod,kafka-pool=nav-dev,image=${{ needs.build.outputs.image }}


  deploy-prod:
    name: Deploy til prod
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til prod-fss
        env:
          CLUSTER: prod-fss
          RESOURCE: nais.yaml
          VAR: spring-profil=prod,kafka-pool=nav-prod,image=${{ needs.build.outputs.image }}
